# This is a basic workflow to help you get started with Actions

name: Build WindowsMac

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v2 branch
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deps
        run: brew install git wget cmake autoconf automake libtool jq python zstd
 
      - name: Get Rack Source
        uses: actions/checkout@v2
        with:
          repository: VCVRack/Rack
          ref: v2
          path: Rack
          submodules: recursive
          
      - name: Build Rack
        working-directory: Rack
        run: |
          make dep
          make

      - name: Get Repo Source
        uses: actions/checkout@v2
        with:
          path: Rack/plugins/AudibleInstruments
          ref: v2
          submodules: recursive

      - name: Build Plugins
        working-directory: Rack/plugins/AudibleInstruments
        run: |
          make dep
          make 
          make dist

      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: mac_build
          path: Rack/plugins/**/dist/*.vcvplugin