# This is a basic workflow to help you get started with Actions

name: Build Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the v2 branch
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup MSYS2
      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with: 
          msystem: MINGW64
          update: true
          install: >-
            git 
            wget 
            make 
            tar 
            unzip
            zip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gdb
            mingw-w64-x86_64-cmake
            autoconf
            automake
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-jq
            python
            zstd
 
      - name: Get Rack Source
        uses: actions/checkout@v2
        with:
          repository: VCVRack/Rack
          ref: v2
          path: Rack
          submodules: recursive
          
     - name: Build Rack
    #    shell: msys2 {0}
       working-directory: Rack
       run: |
         make dep
         make